AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ApiKey:
    Description: >-
      Your Datadog API Key
    Type: String
    AllowedPattern: .+
    ConstraintDescription: ApiKey is required
    NoEcho: true
  Regions:
    Description: >-
      Comma separated list of regions to enable metric streaming
    Type: CommaDelimitedList
    ConstraintDescription: Regions is required
    Default: ''
  DdSite:
    Type: String
    Default: datadoghq.com
    Description: Define your Datadog Site to send data to. For example, datadoghq.eu or us5.datadoghq.com
    AllowedPattern: .+
    ConstraintDescription: DdSite is required
Resources:
  DatadogEventbridgeStackSetAdministrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "DatadogEventbridgeStackSetAdministrationRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: DatadogEventbridgeCfnStackSetAssumeRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: "*"
  DatadogEventbridgeStackSetExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "DatadogEventbridgeStackSetExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt DatadogEventbridgeStackSetAdministrationRole.Arn
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: DatadogEventbridgeCfnStackAssumeRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "s3:*"
                Resource:
                  - "arn:aws:s3:::cf-templates-*"
              - Effect: Allow
                Action:
                  - "cloudformation:*"
                Resource:
                  - !Sub "arn:aws:cloudformation:*:${AWS::AccountId}:stack/StackSet-DatadogEventbridge-*"
                  - !Sub "arn:aws:cloudformation:*:${AWS::AccountId}:stackset/DatadogEventbridge*"
              - Effect: Allow
                Action:
                  - "sns:Publish"
                Resource:
                  - "arn:aws:sns:*:*:CfnNotificationSNSTopic"
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:PassRole
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                Resource:
                  - !Sub "arn:aws:s3:::datadog-aws-cloudtrail-stream-backup-${AWS::AccountId}-*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:DeleteLogGroup
                  - logs:PutRetentionPolicy
                  - logs:CreateLogStream
                  - logs:DeleteLogStream
                  - logs:DescribeLogStreams
                Resource:
                  - !Sub "arn:aws:logs:*:${AWS::AccountId}:log-group:datadog-cloudtrail-stream*"
              - Effect: Allow
                Action:
                  - firehose:CreateDeliveryStream
                  - firehose:DescribeDeliveryStream
                  - firehose:DeleteDeliveryStream
                Resource:
                  - !Sub "arn:aws:firehose:*:${AWS::AccountId}:deliverystream/datadog-cloudtrail-stream"
              - Effect: Allow
                Action:
                  - events:DescribeRule
                  - events:PutRule
                  - events:DeleteRule
                  - events:PutTargets
                  - events:RemoveTargets
                Resource:
                  - !Sub "arn:aws:events:*:${AWS::AccountId}:rule/datadog-cloudtrail"
  ServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "DatadogCloudtrailServiceRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "firehose.amazonaws.com"
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: "datadog_cloudtrail_stream_s3_policy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:AbortMultipartUpload"
                  - "s3:GetBucketLocation"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                  - "s3:ListBucketMultipartUploads"
                  - "s3:PutObject"
                Resource:
                  - !Sub "arn:aws:s3:::datadog-aws-cloudtrail-stream-backup-${AWS::AccountId}-*"
                  - !Sub "arn:aws:s3:::datadog-aws-cloudtrail-stream-backup-${AWS::AccountId}-*/*"
  DatadogEventbridgeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "DatadogEventbridgeRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: "datadog_eventbridge_invoke_firehose_policy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "firehose:PutRecord"
                  - "firehose:PutRecordBatch"
                Resource:
                  - !Sub "arn:aws:firehose:*:${AWS::AccountId}:deliverystream/datadog-cloudtrail-stream"
      Description: A cloudtrail stream role
  DatadogEventbridgeStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: DatadogEventbridge
      PermissionModel: SELF_MANAGED
      AdministrationRoleARN: !GetAtt DatadogEventbridgeStackSetAdministrationRole.Arn
      ExecutionRoleName: !Ref DatadogEventbridgeStackSetExecutionRole
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref "AWS::AccountId"
          Regions: !Ref Regions
      TemplateURL: "https://s3.amazonaws.com/<BUCKET_PLACEHOLDER>/aws/eventbridge-single-region.yaml"
      Parameters:
        - ParameterKey: ApiKey
          ParameterValue: !Ref ApiKey
        - ParameterKey: ServiceRoleArn
          ParameterValue: !GetAtt ServiceRole.Arn
        - ParameterKey: EventbridgeRoleArn
          ParameterValue: !GetAtt DatadogEventbridgeRole.Arn
        - ParameterKey: DdSite
          ParameterValue: !Ref DdSite
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Required
      Parameters:
        - ApiKey
        - DdSite
        - Regions
    - Label:
        default: Optional
