AWSTemplateFormatVersion: 2010-09-09
Description: Datadog AWS Integration API Call
Parameters:
  RoleName:
    Description: >-
      The name of the IAM role created for Datadog's use.
    Type: String
  HostTags:
    Type: CommaDelimitedList
    Default: ""
    Description: >-
      A comma seperated list of tags to add to hosts and metrics
Resources:
  DatadogAWSAccountIntegration:
    Type: Datadog::Integrations::AWSQuickstart
    Properties:
      AccountID: !Ref AWS::AccountId
      RoleName: !Ref RoleName
      HostTags: !Ref HostTags
