AWSTemplateFormatVersion: 2010-09-09
Description: Datadog AWS Integration
Parameters:
  DdApiKey:
    Description: >-
      API key for the Datadog account
    Type: String
    NoEcho: true
    AllowedPattern: .+
    ConstraintDescription: DdApiKey is required
  DdAppKey:
    Description: >-
      APP key for the Datadog account
    Type: String
    NoEcho: true
    AllowedPattern: .+
    ConstraintDescription: DdAppKey is required
  DdSite:
    Type: String
    Default: datadoghq.com
    Description: Define your Datadog Site to send data to.
    AllowedValues:
      - datadoghq.com
      - datadoghq.eu
      - us3.datadoghq.com
      - us5.datadoghq.com
      - ddog-gov.com
    ConstraintDescription: DdSite is required
  IAMRoleName:
    Description: Customize the name of IAM role for Datadog AWS integration
    Type: String
    Default: DatadogIntegrationRole
  ObservabilityPermissions:
    Description: >-
      Customize the observability permissions for the Datadog IAM role.
      Select "Limited Permissions" to only grant Datadog permissions to monitor a limited set of metrics and metadata
      (not recommended).
    Type: String
    Default: Standard Permissions
    AllowedValues:
      - Standard Permissions
      - Limited Permissions
  LogArchives:
    Description: >-
      S3 paths to store log archives for log rehydration. Separate multiple paths with comma, e.g.,
      "my-bucket,my-bucket-with-path/path". Permissions will be automatically added to the Datadog integration IAM role
      so that Datadog can store log archives in these buckets.
      https://docs.datadoghq.com/logs/archives/rehydrating/?tab=awss3
    Type: String
    Default: ''
  DdForwarderName:
    Type: String
    Default: DatadogForwarder
    Description: >-
      The Datadog Forwarder Lambda function name. DO NOT change when updating an existing CloudFormation stack,
      otherwise the current forwarder function will be replaced and all the triggers will be lost.
  InstallDatadogPolicyMacro:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    Description: If you already deployed a stack using this template, set this parameter to "false" to skip the installation of the DatadogPolicy Macro again.
  CloudSecurityPostureManagementPermissions:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    Description: >-
      Set this value to "true" to add the IAM permissions necessary to use Cloud Security Posture Management.
  HostTags:
    Type: CommaDelimitedList
    Default: ""
    Description: >-
      A comma separated list of tags to add to hosts and metrics. Example: "aws_account:123456789123,account:prod"
Conditions:
  ShouldInstallDatadogPolicyMacro:
    Fn::Equals:
      - Ref: InstallDatadogPolicyMacro
      - true
Resources:
  # A Macro used to generate policies for the integration IAM role based on user inputs
  DatadogPolicyMacroStack:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldInstallDatadogPolicyMacro
    Properties:
      TemplateURL: "https://<BUCKET_PLACEHOLDER>.s3.amazonaws.com/aws/datadog_policy_macro.yaml"
  # Installing the AWS Integration in Datadog
  DatadogAWSIntegration:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://<BUCKET_PLACEHOLDER>.s3.amazonaws.com/aws/datadog_integration_type_config.yaml"
      Parameters:
        APIKey: !Ref DdApiKey
        APPKey: !Ref DdAppKey
        IAMRoleName: !Ref IAMRoleName
        HostTags: !Join [ ",", !Ref HostTags ]
        DdSite: !Ref DdSite
  # The IAM role for Datadog integration
  DatadogIntegrationRoleStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DatadogAWSIntegration
    Properties:
      TemplateURL: "https://<BUCKET_PLACEHOLDER>.s3.amazonaws.com/aws/datadog_integration_role.yaml"
      Parameters:
        # This secret contains the external_id returned by the custom cloudformation resource that calls the Datadog API
        ExternalId: "{{resolve:secretsmanager:DatadogIntegrationExternalID:SecretString:external_id}}"
        ObservabilityPermissions: !Ref ObservabilityPermissions
        IAMRoleName: !Ref IAMRoleName
        LogArchives: !Ref LogArchives
        CloudSecurityPostureManagementPermissions: !Ref CloudSecurityPostureManagementPermissions
        DdAWSAccountId: "464622532012"
      Tags:
        - # A trick to create a conditional dependency on DatadogPolicyMacroStack
          # https://stackoverflow.com/questions/34607476/cloudformation-apply-condition-on-dependson
          Key: "DatadogPolicyMacroStackId"
          Value: !If [ShouldInstallDatadogPolicyMacro, !Ref DatadogPolicyMacroStack, "null"]
  # The Lambda function to ship logs from S3 and CloudWatch, custom metrics and traces from Lambda functions to Datadog
  # https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring
  ForwarderStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://<BUCKET_PLACEHOLDER>.s3.amazonaws.com/aws/datadog_forwarder.yaml"
      Parameters:
        DdApiKey: !Ref DdApiKey
        DdSite: !Ref DdSite
        FunctionName: !Ref DdForwarderName
Outputs:
  IAMRoleName:
    Description: AWS IAM Role named to be used with the DataDog AWS Integration 
    Value: !Ref IAMRoleName
  AccountId:
    Description: AWS Account number
    Value: !Ref "AWS::AccountId"
  Region:
    Description: AWS Region
    Value: !Ref "AWS::Region"
  DatadogForwarderArn:
    Description: Datadog Forwarder Lambda Function ARN
    Value:
      Fn::GetAtt:
        - ForwarderStack
        - Outputs.DatadogForwarderArn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-DatadogForwarderArn
  DdApiKeySecretArn:
    Description: ARN of SecretsManager Secret with Datadog API Key
    Value:
      Fn::GetAtt:
        - ForwarderStack
        - Outputs.DdApiKeySecretArn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ApiKeySecretArn
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Required
      Parameters:
        - DdApiKey
        - DdAppKey
        - DdSite
    - Label:
        default: Advanced
      Parameters:
        - HostTags
        - LogArchives
        - ObservabilityPermissions
        - CloudSecurityPostureManagementPermissions
        - IAMRoleName
        - DdForwarderName
        - InstallDatadogPolicyMacro
    ParameterLabels:
      DdApiKey:
        default: "DdApiKey *"
      DdAppKey:
        default: "DdAppKey *"
      DdSite:
        default: "DdSite *"
