AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ApiKey:
    Description: >-
      Your Datadog API Key
    Type: String
    AllowedPattern: .+
    ConstraintDescription: ApiKey is required
    NoEcho: true
  Regions:
    Description: >-
      Comma separated list of regions to enable metric streaming
    Type: CommaDelimitedList
    ConstraintDescription: Regions is required
    Default: ''
  DatadogSite:
    Type: String
    Default: datadoghq.com
    Description: Define your Datadog Site to send data to.
    AllowedValues:
      - datadoghq.com
      - datadoghq.eu
      - us3.datadoghq.com
      - us5.datadoghq.com
      - ddog-gov.com
    ConstraintDescription: DatadogSite is required
Resources:
  DatadogCloudtrailEventbridgeStackSetAdministrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "DatadogCloudtrailEventbridgeStackSetAdministrationRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: DatadogEventbridgeCfnStackSetAssumeRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: "*"
  DatadogCloudtrailEventbridgeStackSetExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "DatadogCloudtrailEventbridgeStackSetExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt DatadogCloudtrailEventbridgeStackSetAdministrationRole.Arn
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: DatadogEventbridgeCfnStackAssumeRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "s3:*"
                Resource:
                  - "arn:aws:s3:::cf-templates-*"
              - Effect: Allow
                Action:
                  - "cloudformation:*"
                Resource:
                  - !Sub "arn:aws:cloudformation:*:${AWS::AccountId}:stack/StackSet-DatadogCloudtrailEventbridge-*"
                  - !Sub "arn:aws:cloudformation:*:${AWS::AccountId}:stackset/DatadogCloudtrailEventbridge*"
              - Effect: Allow
                Action:
                  - "sns:Publish"
                Resource:
                  - "arn:aws:sns:*:*:CfnNotificationSNSTopic"
              - Effect: Allow
                Action:
                  - iam:GetRole
                  - iam:PassRole
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:PutBucketPublicAccessBlock
                  - s3:PutEncryptionConfiguration
                Resource:
                  - !Sub "arn:aws:s3:::datadog-aws-cloudtrail-backup-${AWS::AccountId}-*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:DeleteLogGroup
                  - logs:PutRetentionPolicy
                  - logs:CreateLogStream
                  - logs:DeleteLogStream
                  - logs:DescribeLogStreams
                Resource:
                  - !Sub "arn:aws:logs:*:${AWS::AccountId}:log-group:datadog-eventbridge-cloudtrail-stream*"
              - Effect: Allow
                Action:
                  - firehose:CreateDeliveryStream
                  - firehose:DescribeDeliveryStream
                  - firehose:DeleteDeliveryStream
                Resource:
                  - !Sub "arn:aws:firehose:*:${AWS::AccountId}:deliverystream/datadog-eventbridge-cloudtrail-stream"
              - Effect: Allow
                Action:
                  - events:DescribeRule
                  - events:PutRule
                  - events:DeleteRule
                  - events:PutTargets
                  - events:RemoveTargets
                Resource:
                  - !Sub "arn:aws:events:*:${AWS::AccountId}:rule/datadog-eventbridge-cloudtrail"
  DatadogCloudtrailServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "DatadogCloudtrailServiceRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "firehose.amazonaws.com"
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: "datadog_cloudtrail_stream_s3_policy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:AbortMultipartUpload"
                  - "s3:GetBucketLocation"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                  - "s3:ListBucketMultipartUploads"
                  - "s3:PutObject"
                Resource:
                  - !Sub "arn:aws:s3:::datadog-aws-cloudtrail-backup-${AWS::AccountId}-*"
                  - !Sub "arn:aws:s3:::datadog-aws-cloudtrail-backup-${AWS::AccountId}-*/*"
  DatadogCloudtrailEventbridgeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "DatadogCloudtrailEventbridgeRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: "datadog_eventbridge_invoke_firehose_policy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "firehose:PutRecord"
                  - "firehose:PutRecordBatch"
                Resource:
                  - !Sub "arn:aws:firehose:*:${AWS::AccountId}:deliverystream/datadog-eventbridge-cloudtrail-stream"
      Description: A cloudtrail stream role
  DatadogCloudtrailEventbridgeStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: DatadogCloudtrailEventbridge
      PermissionModel: SELF_MANAGED
      AdministrationRoleARN: !GetAtt DatadogCloudtrailEventbridgeStackSetAdministrationRole.Arn
      ExecutionRoleName: !Ref DatadogCloudtrailEventbridgeStackSetExecutionRole
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref "AWS::AccountId"
          Regions: !Ref Regions
      TemplateURL: "https://s3.amazonaws.com/<BUCKET_PLACEHOLDER>/aws/eventbridge-single-region.yaml"
      Parameters:
        - ParameterKey: ApiKey
          ParameterValue: !Ref ApiKey
        - ParameterKey: DatadogCloudtrailServiceRoleArn
          ParameterValue: !GetAtt DatadogCloudtrailServiceRole.Arn
        - ParameterKey: DatadogCloudtrailEventbridgeRoleArn
          ParameterValue: !GetAtt DatadogCloudtrailEventbridgeRole.Arn
        - ParameterKey: DatadogSite
          ParameterValue: !Ref DatadogSite
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Required
      Parameters:
        - ApiKey
        - DatadogSite
        - Regions
